[2023-10-23 14:42:26] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to Too many packets lost
[2023-10-23 14:42:27] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to Too many packets lost
[2023-10-23 14:43:28] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to Too many packets lost
[2023-10-23 14:43:29] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to Too many packets lost
[2023-10-23 15:20:22] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:20:22] [WARNING] Failed to connect to radio://0/27/2M/E7E7E7E702 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:20:22] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:20:30] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:20:30] [WARNING] Failed to connect to radio://0/27/2M/E7E7E7E702 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:20:30] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:20:39] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:20:39] [WARNING] Failed to connect to radio://0/27/2M/E7E7E7E702 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:20:39] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:20:49] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:20:49] [WARNING] Failed to connect to radio://0/27/2M/E7E7E7E702 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:20:49] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:21:09] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:21:09] [WARNING] Failed to connect to radio://0/27/2M/E7E7E7E702 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:21:09] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:21:59] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:21:59] [WARNING] Failed to connect to radio://0/27/2M/E7E7E7E702 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:21:59] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:22:37] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to name 'syncCrazyflie' is not defined
[2023-10-23 15:22:37] [WARNING] Failed to connect to radio://0/27/2M/E7E7E7E702 due to name 'syncCrazyflie' is not defined
[2023-10-23 15:22:37] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to name 'syncCrazyflie' is not defined
[2023-10-23 15:23:10] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to name 'syncCrazyflie' is not defined
[2023-10-23 15:23:10] [WARNING] Failed to connect to radio://0/27/2M/E7E7E7E702 due to name 'syncCrazyflie' is not defined
[2023-10-23 15:23:10] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to name 'syncCrazyflie' is not defined
[2023-10-23 15:24:34] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to name 'syncCrazyflie' is not defined
[2023-10-23 15:24:34] [WARNING] Failed to connect to radio://0/27/2M/E7E7E7E702 due to name 'syncCrazyflie' is not defined
[2023-10-23 15:24:34] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to name 'syncCrazyflie' is not defined
[2023-10-23 15:25:31] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to Too many packets lost
[2023-10-23 15:26:12] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to Too many packets lost
[2023-10-23 15:28:27] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:28:27] [WARNING] Failed to connect to radio://0/27/2M/E7E7E7E702 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:28:27] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:28:43] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to Too many packets lost
[2023-10-23 15:43:45] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:43:45] [WARNING] Failed to connect to radio://0/27/2M/E7E7E7E702 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:43:45] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:44:31] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:44:31] [WARNING] Failed to connect to radio://0/27/2M/E7E7E7E702 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:44:31] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to name 'SyncCrazyflie' is not defined
[2023-10-23 15:45:36] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to Too many packets lost
[2023-10-23 15:56:02] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to Too many packets lost
[2023-10-23 16:02:30] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to Too many packets lost
[2023-10-23 16:02:52] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to Too many packets lost
[2023-10-23 16:02:57] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to Too many packets lost
[2023-12-10 23:06:28] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 124, in __init__
    device = _find_devices()[devid]
             ^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 79, in _find_devices
    devices = usb.core.find(idVendor=0x1915, idProduct=0x7777, find_all=1,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crazyflie\__init__.py", line 231, in open_link
    self.link = cflib.crtp.get_link_driver(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\__init__.py", line 99, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 265, in connect
    self._radio = RadioManager.open(devid)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 224, in open
    shared_radio = _SharedRadio(devid)
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 147, in __init__
    self._radio = Crazyradio(devid=devid)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 129, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

[2023-12-10 23:06:28] [WARNING] Failed to connect to radio://0/27/2M/E7E7E7E702 due to Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 124, in __init__
    device = _find_devices()[devid]
             ^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 79, in _find_devices
    devices = usb.core.find(idVendor=0x1915, idProduct=0x7777, find_all=1,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crazyflie\__init__.py", line 231, in open_link
    self.link = cflib.crtp.get_link_driver(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\__init__.py", line 99, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 265, in connect
    self._radio = RadioManager.open(devid)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 224, in open
    shared_radio = _SharedRadio(devid)
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 147, in __init__
    self._radio = Crazyradio(devid=devid)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 129, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

[2023-12-10 23:06:28] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 124, in __init__
    device = _find_devices()[devid]
             ^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 79, in _find_devices
    devices = usb.core.find(idVendor=0x1915, idProduct=0x7777, find_all=1,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crazyflie\__init__.py", line 231, in open_link
    self.link = cflib.crtp.get_link_driver(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\__init__.py", line 99, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 265, in connect
    self._radio = RadioManager.open(devid)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 224, in open
    shared_radio = _SharedRadio(devid)
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 147, in __init__
    self._radio = Crazyradio(devid=devid)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 129, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

[2023-12-11 21:58:19] [WARNING] Failed to connect to radio://0/80/2M/E7E7E7E701 due to Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 124, in __init__
    device = _find_devices()[devid]
             ^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 79, in _find_devices
    devices = usb.core.find(idVendor=0x1915, idProduct=0x7777, find_all=1,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crazyflie\__init__.py", line 231, in open_link
    self.link = cflib.crtp.get_link_driver(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\__init__.py", line 99, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 265, in connect
    self._radio = RadioManager.open(devid)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 224, in open
    shared_radio = _SharedRadio(devid)
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 147, in __init__
    self._radio = Crazyradio(devid=devid)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 129, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

[2023-12-11 21:58:19] [WARNING] Failed to connect to radio://0/27/2M/E7E7E7E702 due to Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 124, in __init__
    device = _find_devices()[devid]
             ^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 79, in _find_devices
    devices = usb.core.find(idVendor=0x1915, idProduct=0x7777, find_all=1,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crazyflie\__init__.py", line 231, in open_link
    self.link = cflib.crtp.get_link_driver(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\__init__.py", line 99, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 265, in connect
    self._radio = RadioManager.open(devid)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 224, in open
    shared_radio = _SharedRadio(devid)
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 147, in __init__
    self._radio = Crazyradio(devid=devid)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 129, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

[2023-12-11 21:58:19] [WARNING] Failed to connect to radio://0/28/2M/E7E7E7E703 due to Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 124, in __init__
    device = _find_devices()[devid]
             ^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 79, in _find_devices
    devices = usb.core.find(idVendor=0x1915, idProduct=0x7777, find_all=1,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crazyflie\__init__.py", line 231, in open_link
    self.link = cflib.crtp.get_link_driver(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\__init__.py", line 99, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 265, in connect
    self._radio = RadioManager.open(devid)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 224, in open
    shared_radio = _SharedRadio(devid)
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\crtp\radiodriver.py", line 147, in __init__
    self._radio = Crazyradio(devid=devid)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cflib\drivers\crazyradio.py", line 129, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

